#!/usr/bin/env python3
"""Generate a lightweight EOB index from the CSV data layer."""

from __future__ import annotations

import csv
from pathlib import Path


SOURCE = Path("data/papers/eob_candidates.csv")
TARGET = Path("topics/eob/generated-index.md")


def main() -> int:
    if not SOURCE.exists():
        print(f"ERROR: missing {SOURCE}")
        return 1

    with SOURCE.open(newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))

    rows.sort(key=lambda row: (row.get("year", ""), row.get("arxiv_id", "")))

    lines = [
        "# EOB Generated Index",
        "",
        "This file is generated by `scripts/build_topic_index.py` from `data/papers/eob_candidates.csv`.",
        "Do not edit this file by hand. Edit the CSV data layer or the curated `literature.md` instead.",
        "",
        "| Year | arXiv | Title | Tags | URL |",
        "| --- | --- | --- | --- | --- |",
    ]

    for row in rows:
        year = row.get("year", "")
        arxiv_id = row.get("arxiv_id", "")
        title = (row.get("title", "") or "").replace("|", "\\|")
        tags = (row.get("technical_tags", "") or "").replace("|", "\\|")
        url = row.get("url", "")
        lines.append(f"| {year} | {arxiv_id} | {title} | {tags} | {url} |")

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"generated {TARGET} rows={len(rows)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
